name: Simulasi CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Jalankan perintah simulasi
      run: echo "Simulasi CI berjalan dengan sukses!"
